/*
Alex Look
CSC 355 Section 402
Assignment 4
10/12/20
*/
-- 1. 
SELECT ID, NAME, STARTDATE
    FROM MEMBER
    WHERE CLUBID in (SELECT ID
                    FROM CLUB
                    WHERE City='Gurnee' AND STATE='IL')
    ORDER BY STARTDATE DESC;
-- 2. 
SELECT ID, NAME
    FROM MEMBER
    WHERE CLUBID in (SELECT CLUBID
                    FROM CLASS
                    WHERE NAME LIKE '%Yoga%');
-- 3. 
SELECT COUNT(NAME), SUM (FEE)
    FROM MEMBER
    WHERE FEE >=60;
-- 4. 
SELECT NAME, ID
    FROM REGISTRATION RIGHT OUTER JOIN CLASS on REGISTRATION.CLASSID=CLASS.ID
    WHERE CLASSID is NULL
    ORDER BY NAME ASC;
-- 5. 
SELECT NAME, AGE
    FROM MEMBER
    WHERE AGE<=30 AND  CLUBID in (SELECT CLUBID
                                  FROM CLASS
                                  WHERE NAME LIKE '%Cardio%')
    ORDER BY AGE DESC;
-- 6. 
SELECT CLUBID, MIN(STARTDATE)
    FROM CLUB inner join MEMBER on CLUB.ID=MEMBER.CLUBID
    GROUP BY CLUBID
    ORDER BY CLUBID ASC;
-- 7. 
SELECT MEMBERID, COUNT(CLASSID)
    FROM REGISTRATION
    GROUP BY MEMBERID
    HAVING COUNT(CLASSID)>=4
    ORDER BY COUNT(CLASSID) ASC;
-- 8. 
SELECT CLUB.ID, CLUB.CITY, COUNT(CLUBID), MIN(AGE)
    FROM MEMBER RIGHT OUTER JOIN CLUB on MEMBER.CLUBID=CLUB.ID
    WHERE STATE='IL'
    GROUP BY CLUB.ID, CLUB.CITY
    ORDER BY COUNT(CLUBID) ASC;