/*
Alex Look
CSC 355 Section 402
Assignment 3
10/5/20
*/
-- 1.
SELECT DISTINCT CCity
    FROM CUSTOMER
    WHERE CSHIPPER='UPS'
    ORDER BY CCity ASC;
-- 2.
SELECT INAME, IPRICE
    FROM ITEM
    WHERE IDEPT='DVDs'
    ORDER BY IPRICE DESC;
-- 3.
SELECT INAME, IPRICE, IDEPT
    FROM ITEM
    WHERE IPRICE>17.99
    ORDER BY IPRICE ASC;
-- 4.
SELECT INAME
    FROM ITEM
    WHERE INAME LIKE '%East%'
    ORDER BY INAME ASC;
-- 5.
SELECT IDEPT, MIN(IPRICE)
    FROM ITEM
    GROUP BY IDEPT
    ORDER BY IDEPT ASC;
-- 6.
SELECT CUSTOMERID, MAX(RDATE)
    FROM REQUEST
    GROUP BY CUSTOMERID
    ORDER BY CUSTOMERID ASC;    
-- 7.
SELECT COUNT(RID),RDATE,SUM(RQUANTITY)
    FROM REQUEST
    GROUP BY RQUANTITY, RDATE
    ORDER BY COUNT(RID) ASC;
-- 8.
SELECT RID, RDATE
    FROM CUSTOMER inner join REQUEST on cid=CUSTOMERID
    WHERE CNAME='Monroe'
    ORDER BY RID ASC;    
-- 9.
SELECT DISTINCT(CID), CNAME
    FROM CUSTOMER inner join REQUEST on cid=CUSTOMERID
    WHERE RDATE>= DATE'01-JAN-2019'AND RDATE<=DATE'31-DEC-2019'
    ORDER BY CID ASC;    
-- 10.
SELECT RID, (RQUANTITY*IPRICE)
    FROM REQUEST inner join ITEM on IID=ITEMID
    ORDER BY (RQUANTITY*IPRICE) DESC;